name: ci
on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ubuntu:20.04

    steps:
      - uses: actions/checkout@v2
      - name: system bootstrap
        run: |
          bash ci/deb_install.sh

      - name: git clone linux
        shell: bash
        run: |
          wget -c -q https://github.com/torvalds/linux/archive/refs/tags/v5.4.zip
          unzip -q v5.4.zip
          make -C linux-5.4/tools/perf
          mkdir linux5.4_perf
          mv linux-5.4/tools/perf linux5.4_perf/
          tar cvzf linux5.4_perf.tar.gz ./linux5.4_perf

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Development Build"
          files: |
            linux5.4_perf.tar.gz