name: ci
on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ubuntu:20.04

    steps:
      - uses: actions/checkout@v2
      - name: system bootstrap
        run: |
          bash ci/deb_install.sh

      - name: git clone linux
        shell: bash
        run: |
          bash scripts/build_for_linux.sh 4.15
          bash scripts/build_for_linux.sh 5.4
          bash scripts/build_for_linux.sh 3.10

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Development Build"
          files: |
            linux_*_perf.tar.gz